/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ObectsAndClasses;

/**
 *
 * @author Kyrab
 */
public class ClientInterface extends javax.swing.JFrame {

    /**
     * Creates new form ClientInterface
     */
    public ClientInterface() {
        initComponents();
    }

    public static String nameChanged;
    public static String number;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        accountNbr = new javax.swing.JTextField();
        balance = new javax.swing.JTextField();
        lientB = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        deetsF = new javax.swing.JTextField();
        showDetailB = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(accountNbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 129, 21));
        getContentPane().add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 129, -1));

        lientB.setText("add client");
        lientB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lientBActionPerformed(evt);
            }
        });
        getContentPane().add(lientB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, -1));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 129, -1));

        deetsF.setEditable(false);
        deetsF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deetsFActionPerformed(evt);
            }
        });
        getContentPane().add(deetsF, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 30, 143, 97));

        showDetailB.setText("show deets");
        showDetailB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDetailBActionPerformed(evt);
            }
        });
        getContentPane().add(showDetailB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void lientBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lientBActionPerformed
        // TODO add your handling code here:    public static String calling;
        String calling;

        double balanceNbr;
        String balanceStr;

        calling = name.getText();
        number = accountNbr.getText();
        balanceStr = balance.getText();
        balanceNbr = Double.parseDouble(balanceStr);
        Client client1 = new Client(calling, number, balanceNbr);

        nameChanged = client1.changeName();
    }//GEN-LAST:event_lientBActionPerformed

    private void showDetailBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDetailBActionPerformed
        // TODO add your handling code here:
        deetsF.setText("Name:" + nameChanged + "\n");
        deetsF.setText("Account number: " + number + "\n");
        deetsF.setText(" Account Balance:" + balanceStr + "\n");


    }//GEN-LAST:event_showDetailBActionPerformed

    private void deetsFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deetsFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deetsFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNbr;
    private javax.swing.JTextField balance;
    private javax.swing.JTextField deetsF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton lientB;
    private javax.swing.JTextField name;
    private javax.swing.JButton showDetailB;
    // End of variables declaration//GEN-END:variables
}
